version: '3'

services:
  react-development:
    # container_name: react-development # Comment container_name to use deploy script (Zero downtime deployment)
    image: react/development
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile
    expose:
      - 80
    env_file:
      - .env

networks:
  default:
    external:
      name: nginx-proxy
