version: '3'

services:
  react-production:
    image: react/production
    # container_name: react-production # Comment container_name to use deploy script (Zero downtime deployment)
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.production
    restart: always
    env_file:
      - .env.production
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
