version: '3.6'

services:

  php-local:
    image: php/fpm74
    container_name: php-local
    restart: always
    volumes:
      - ./:/var/www/public/dev.localhost # document_root Location required if your site running php
    env_file:
      - ./env/local.env
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
