version: '3.6'

services:
  api-development:
    # container_name: api-development # Dont use container_name in deployment server
    image: api/development
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile
    expose:
      - 80
    env_file:
      - .env

networks:
  default:
    external:
      name: nginx-proxy
