version: '3.9'

services:
  api-local:
    container_name: api-local
    image: express/api-local
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.local
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./env/local.env
    command:
      - nodemon
      - --inspect=0.0.0.0:9229
      - server.js
    expose:
      - 80
