version: '3.6'

services:
  api-production:
    # container_name: express-api # Dont use container_name in production server
    image: api/production
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile.production
    env_file:
      - ./env/production.env
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
